/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href: string
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type ItineraryDay = {
  _type: 'itineraryDay'
  day: number
  title: string
  description?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  identifier: 'about' | 'faq'
  content?: BlockContent
  faqItems?: Array<{
    question: string
    answer?: string
    _type: 'faqItem'
    _key: string
  }>
}

export type ApplicationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'application'
}

export type TripReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'trip'
}

export type Booking = {
  _id: string
  _type: 'booking'
  _createdAt: string
  _updatedAt: string
  _rev: string
  application: ApplicationReference
  trip: TripReference
  depositPaid?: boolean
  depositPaidDate?: string
  balancePaid?: boolean
  balancePaidDate?: string
  balanceDueDate?: string
  portalAccessGranted?: boolean
  supabaseUserId?: string
}

export type Application = {
  _id: string
  _type: 'application'
  _createdAt: string
  _updatedAt: string
  _rev: string
  trip: TripReference
  firstName: string
  lastName: string
  email: string
  phone?: string
  dateOfBirth?: string
  nationality?: string
  experienceLevel?: 'beginner' | 'some' | 'experienced' | 'expert'
  motivation?: string
  emergencyContact?: {
    name?: string
    phone?: string
  }
  medicalInfo?: string
  status: 'pending' | 'approved' | 'rejected'
  submittedAt?: string
  reviewedAt?: string
  reviewNotes?: string
}

export type Trip = {
  _id: string
  _type: 'trip'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  destination: string
  startDate: string
  endDate: string
  price?: {
    deposit: number
    total: number
    currency?: 'EUR' | 'USD' | 'GBP'
  }
  maxGroupSize: number
  difficultyLevel: 'easy' | 'moderate' | 'challenging' | 'expert'
  status: 'open' | 'full' | 'archived'
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  shortDescription: string
  fullDescription?: BlockContent
  itinerary?: Array<
    {
      _key: string
    } & ItineraryDay
  >
  included?: Array<string>
  excluded?: Array<string>
  packingList?: BlockContentTextOnly
  meetingPoint?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroHeading?: string
  heroSubheading?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  introText?: string
  featuredTrips?: Array<
    {
      _key: string
    } & TripReference
  >
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | BlockContentTextOnly
  | SanityImageAssetReference
  | BlockContent
  | ItineraryDay
  | Page
  | ApplicationReference
  | TripReference
  | Booking
  | Application
  | Trip
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && _id == "siteSettings"][0]{    heroHeading,    heroSubheading,    heroImage,    introText,    "featuredTrips": featuredTrips[]->{      _id,      title,      "slug": slug.current,      destination,      startDate,      endDate,      shortDescription,      difficultyLevel,      status,      "price": price{deposit, total, currency},      heroImage,    },    ogImage,  }
export type SettingsQueryResult = {
  heroHeading: string | null
  heroSubheading: string | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  introText: string | null
  featuredTrips: Array<{
    _id: string
    title: string
    slug: string
    destination: string
    startDate: string
    endDate: string
    shortDescription: string
    difficultyLevel: 'challenging' | 'easy' | 'expert' | 'moderate'
    status: 'archived' | 'full' | 'open'
    price: {
      deposit: number
      total: number
      currency: 'EUR' | 'GBP' | 'USD' | null
    } | null
    heroImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  }> | null
  ogImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: allTripsQuery
// Query: *[_type == "trip" && status != "archived"] | order(startDate asc){    _id,    title,    "slug": slug.current,    destination,    startDate,    endDate,    shortDescription,    difficultyLevel,    status,    "price": price{deposit, total, currency},    heroImage,    maxGroupSize,  }
export type AllTripsQueryResult = Array<{
  _id: string
  title: string
  slug: string
  destination: string
  startDate: string
  endDate: string
  shortDescription: string
  difficultyLevel: 'challenging' | 'easy' | 'expert' | 'moderate'
  status: 'archived' | 'full' | 'open'
  price: {
    deposit: number
    total: number
    currency: 'EUR' | 'GBP' | 'USD' | null
  } | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  maxGroupSize: number
}>

// Source: sanity/lib/queries.ts
// Variable: tripBySlugQuery
// Query: *[_type == "trip" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    destination,    startDate,    endDate,    shortDescription,    fullDescription,    difficultyLevel,    status,    "price": price{deposit, total, currency},    maxGroupSize,    heroImage,    gallery,    itinerary,    included,    excluded,    meetingPoint,    packingList,  }
export type TripBySlugQueryResult = {
  _id: string
  title: string
  slug: string
  destination: string
  startDate: string
  endDate: string
  shortDescription: string
  fullDescription: BlockContent | null
  difficultyLevel: 'challenging' | 'easy' | 'expert' | 'moderate'
  status: 'archived' | 'full' | 'open'
  price: {
    deposit: number
    total: number
    currency: 'EUR' | 'GBP' | 'USD' | null
  } | null
  maxGroupSize: number
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  gallery: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }> | null
  itinerary: Array<
    {
      _key: string
    } & ItineraryDay
  > | null
  included: Array<string> | null
  excluded: Array<string> | null
  meetingPoint: string | null
  packingList: BlockContentTextOnly | null
} | null

// Source: sanity/lib/queries.ts
// Variable: tripSlugsQuery
// Query: *[_type == "trip" && defined(slug.current)]{"slug": slug.current}
export type TripSlugsQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pageContentQuery
// Query: *[_type == "page" && identifier == $identifier][0]{    _id,    identifier,    content,    faqItems,  }
export type PageContentQueryResult = {
  _id: string
  identifier: 'about' | 'faq'
  content: BlockContent | null
  faqItems: Array<{
    question: string
    answer?: string
    _type: 'faqItem'
    _key: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "trip" && defined(slug.current)]{    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string
  _type: 'trip'
  _updatedAt: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "settings" && _id == "siteSettings"][0]{\n    heroHeading,\n    heroSubheading,\n    heroImage,\n    introText,\n    "featuredTrips": featuredTrips[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      destination,\n      startDate,\n      endDate,\n      shortDescription,\n      difficultyLevel,\n      status,\n      "price": price{deposit, total, currency},\n      heroImage,\n    },\n    ogImage,\n  }\n': SettingsQueryResult
    '\n  *[_type == "trip" && status != "archived"] | order(startDate asc){\n    _id,\n    title,\n    "slug": slug.current,\n    destination,\n    startDate,\n    endDate,\n    shortDescription,\n    difficultyLevel,\n    status,\n    "price": price{deposit, total, currency},\n    heroImage,\n    maxGroupSize,\n  }\n': AllTripsQueryResult
    '\n  *[_type == "trip" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    destination,\n    startDate,\n    endDate,\n    shortDescription,\n    fullDescription,\n    difficultyLevel,\n    status,\n    "price": price{deposit, total, currency},\n    maxGroupSize,\n    heroImage,\n    gallery,\n    itinerary,\n    included,\n    excluded,\n    meetingPoint,\n    packingList,\n  }\n': TripBySlugQueryResult
    '\n  *[_type == "trip" && defined(slug.current)]{"slug": slug.current}\n': TripSlugsQueryResult
    '\n  *[_type == "page" && identifier == $identifier][0]{\n    _id,\n    identifier,\n    content,\n    faqItems,\n  }\n': PageContentQueryResult
    '\n  *[_type == "trip" && defined(slug.current)]{\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
  }
}
